# Generated by Django 2.1.2 on 2019-01-06 12:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eventType', models.CharField(choices=[('Appointment', 'Appointment'), ('Meeting', 'Meeting'), ('Task', 'Task'), ('All_day', 'All day event'), ('Reccurence_meeting', 'Recurrence meeting')], default='Task', max_length=18)),
                ('eventCategory', models.CharField(choices=[('Red', 'Red category'), ('Blue', 'Blue category'), ('Green', 'Green category'), ('Orange', 'Orange category'), ('Yellow', 'Yellow category')], max_length=10)),
                ('subject', models.TextField(max_length=1000)),
                ('startDate', models.DateField(default=django.utils.timezone.now, help_text='Date of Event start')),
                ('startTime', models.TimeField(default=django.utils.timezone.now, help_text='Date of Event start')),
                ('endDate', models.DateField(default=django.utils.timezone.now, help_text='Time of Event end')),
                ('endTime', models.TimeField(default=django.utils.timezone.now, help_text='Time of Event end')),
                ('place', models.TextField(blank=True, help_text='The place where Event appears', max_length=500, null=True)),
                ('description', models.TextField(blank=True, help_text='Description of Event', max_length=500, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
