# Generated by Django 2.1.2 on 2018-10-21 13:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.TextField(max_length=1000)),
                ('startDateTime', models.DateTimeField()),
                ('endDateTime', models.DateTimeField()),
                ('place', models.TextField(max_length=500, null=True)),
                ('description', models.TextField(max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='EventFlag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flag', models.TextField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='EventType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.TextField(max_length=255, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='event',
            name='eventFlag',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='event.EventFlag'),
        ),
        migrations.AddField(
            model_name='event',
            name='eventType',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='event.EventType'),
        ),
        migrations.AddField(
            model_name='event',
            name='userID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
