# Generated by Django 2.1.2 on 2018-12-28 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='eventFlag',
        ),
        migrations.AddField(
            model_name='event',
            name='eventCategory',
            field=models.CharField(choices=[('Red', 'Red category'), ('Blue', 'Blue category'), ('Green', 'Green category'), ('Orange', 'Orange category'), ('Yellow', 'Yellow category')], default='Red', max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='event',
            name='description',
            field=models.TextField(blank=True, help_text='Description of Event', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='endDateTime',
            field=models.DateTimeField(help_text='Date and time of Event end'),
        ),
        migrations.AlterField(
            model_name='event',
            name='eventType',
            field=models.CharField(choices=[('Appointment', 'Appointment'), ('Meeting', 'Meeting'), ('Task', 'Task'), ('All_day', 'All day event'), ('Reccurence_meeting', 'Recurrence meeting')], default='Task', max_length=18),
        ),
        migrations.AlterField(
            model_name='event',
            name='place',
            field=models.TextField(blank=True, help_text='The place where Event appears', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='startDateTime',
            field=models.DateTimeField(help_text='Date and time of Event start'),
        ),
        migrations.DeleteModel(
            name='EventFlag',
        ),
        migrations.DeleteModel(
            name='EventType',
        ),
    ]
