# Generated by Django 2.1.2 on 2019-01-05 15:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0002_auto_20181228_1344'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='userID',
            new_name='user',
        ),
        migrations.RemoveField(
            model_name='event',
            name='endDateTime',
        ),
        migrations.RemoveField(
            model_name='event',
            name='startDateTime',
        ),
        migrations.AddField(
            model_name='event',
            name='endDate',
            field=models.TimeField(default=django.utils.timezone.now, help_text='Time of Event end'),
        ),
        migrations.AddField(
            model_name='event',
            name='endTime',
            field=models.TimeField(default=django.utils.timezone.now, help_text='Time of Event end'),
        ),
        migrations.AddField(
            model_name='event',
            name='startDate',
            field=models.DateField(default=django.utils.timezone.now, help_text='Date of Event start'),
        ),
        migrations.AddField(
            model_name='event',
            name='startTime',
            field=models.DateField(default=django.utils.timezone.now, help_text='Date of Event start'),
        ),
    ]
